AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
Globals:
  Function:
    Timeout: 5

Parameters:
  SsmPath:
    Type: String
    Default: /sample/dotenv
    Description: ssm prameter key path for dotenv body
  DomainName:
    Type: String
    Default: sample.akiho.app
    Description: api service domain name
  HostedZoneName:
    Type: String
    Default: akiho.app.
    Description: hosted zone name for service domain
  CertificateArn:
    Type: String
    Default: arn:aws:acm:ap-northeast-1:326914400610:certificate/703134f6-9e3b-40ba-aeb2-b9278b60ac6f
    Description: certificate arn for service domain

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target_lambda/deploy.zip
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      MemorySize: 128
      Tracing: Active
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          SSM_PATH: !Ref SsmPath
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
        - AmazonCognitoPowerUser
        - AmazonSESFullAccess
        - AmazonS3FullAccess

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      BinaryMediaTypes:
        - "*/*"
#      Domain:
#        EndpointConfiguration: REGIONAL
#        DomainName: !Ref DomainName
#        Route53:
#          HostedZoneName: !Ref HostedZoneName
#        CertificateArn: !Ref CertificateArn
